import ast 
import re 
import pandas as pd
def extract_response_dict(text: str) -> dict | None:
    """
    Extracts the first Python-style dictionary from a model response string. Very helpful for applying into the LLM_output column of a DataFrame.
    Args:
        text (str): The model response string containing a dictionary.

    Returns:
        dict if successful
        None if extraction or parsing fails
    """
    if not isinstance(text, str):
        return None

    # Match the first {...} block (non-greedy)
    match = re.search(r"\{.*?\}", text, re.DOTALL)

    if not match:
        return None

    dict_str = match.group(0)

    try:
        # Safely parse Python literal
        return ast.literal_eval(dict_str)
    except (SyntaxError, ValueError):
        return None

def parse_report(report: str) -> str:
  """
  We only want the FINDINGS and IMPRESSION parts. Use on bnpp_reports.csv file to clean up the full report.
  """
  match = re.search(r'\bFINDINGS\b.*', report, flags=re.IGNORECASE | re.DOTALL)
  return match.group(0).strip() if match else None

def normalize_severity(sev):
    """
    Function to help normalize the outputs of the medihphi output labels on severity of edema due to the potential of LLM 
    creating labels that were not of the main six. (i.e NA, unknown, trace, mild, moderate, severe)
    
    :param sev: Description generated by the LLM for severity of edema
    """
    if pd.isna(sev):
        return "unknown"

    s = str(sev).lower().strip()

    # exact / clean cases first
    if s in {"na", "n/a"}:
        return "NA"
    if s == "unknown":
        return "unknown"
    if s == "trace":
        return "trace"
    if s == "mild":
        return "mild"
    if s == "moderate":
        return "moderate"
    if s == "severe":
        return "severe"

    # compound / messy cases
    if "mild" in s and "moderate" in s:
        return "moderate"   # conservative: push upward
    if "minimal" in s:
        return "trace"

    # fallback
    return "unknown"
